### ISSUE TITLE
Jais-13B RuntimeError: mismatch dimension of tensor a (2048) and b (2153).

### ISSUE THREAD

**Issue by ashmalvayani** [mbzuai-nlp/ArabicMMLU#1]
When running the following command for jais-13b:

> python evaluate.py --base_model='core42/jais-13b' --lora_weights='x' --lang_alpa='ar' --lang_prompt='ar'

I am getting the following error:
RuntimeError: The size of tensor a (2048) must match the size of tensor b (2153) at non-singleton dimension 3.

**Comment by MeshalAlamr** [comment]
@ashmalvayani I'm getting the same error for the same command, did you manage to solve it?

**Comment by MeshalAlamr** [comment]
Alright, figured it out. It happens because some of the samples in the data exceed jais-13b's context window.

**Comment by ashmalvayani** [comment]
Yes, just add the model name in the if condition where it sets the model to truncate it's input size.
